export interface BulkMarket {
    id: string;
    label: string;
}

/** Bulk Trader market dropdown — same list and order as the legacy desk. */
export const BULK_TRADER_MARKETS: BulkMarket[] = [
    { id: '1HZ100V', label: 'Volatility 100 (1s) Index' },
    { id: '1HZ10V', label: 'Volatility 10 (1s) Index' },
    { id: '1HZ15V', label: 'Volatility 15 (1s) Index' },
    { id: '1HZ25V', label: 'Volatility 25 (1s) Index' },
    { id: '1HZ30V', label: 'Volatility 30 (1s) Index' },
    { id: '1HZ50V', label: 'Volatility 50 (1s) Index' },
    { id: '1HZ75V', label: 'Volatility 75 (1s) Index' },
    { id: '1HZ90V', label: 'Volatility 90 (1s) Index' },
    { id: 'BOOM1000', label: 'Boom 1000 Index' },
    { id: 'BOOM150', label: 'Boom 150 Index' },
    { id: 'BOOM300N', label: 'Boom 300 Index' },
    { id: 'BOOM50', label: 'Boom 50 Index' },
    { id: 'BOOM500', label: 'Boom 500 Index' },
    { id: 'BOOM600', label: 'Boom 600 Index' },
    { id: 'BOOM900', label: 'Boom 900 Index' },
    { id: 'CRASH1000', label: 'Crash 1000 Index' },
    { id: 'CRASH150', label: 'Crash 150 Index' },
    { id: 'CRASH300N', label: 'Crash 300 Index' },
    { id: 'CRASH50', label: 'Crash 50 Index' },
    { id: 'CRASH500', label: 'Crash 500 Index' },
    { id: 'CRASH600', label: 'Crash 600 Index' },
    { id: 'CRASH900', label: 'Crash 900 Index' },
    { id: 'JD10', label: 'Jump 10 Index' },
    { id: 'JD100', label: 'Jump 100 Index' },
    { id: 'JD25', label: 'Jump 25 Index' },
    { id: 'JD50', label: 'Jump 50 Index' },
    { id: 'JD75', label: 'Jump 75 Index' },
    { id: 'RB100', label: 'Range Break 100 Index' },
    { id: 'RB200', label: 'Range Break 200 Index' },
    { id: 'RDBEAR', label: 'Bear Market Index' },
    { id: 'RDBULL', label: 'Bull Market Index' },
    { id: 'R_10', label: 'Volatility 10 Index' },
    { id: 'R_100', label: 'Volatility 100 Index' },
    { id: 'R_25', label: 'Volatility 25 Index' },
    { id: 'R_50', label: 'Volatility 50 Index' },
    { id: 'R_75', label: 'Volatility 75 Index' },
    { id: 'stpRNG', label: 'Step Index 100' },
    { id: 'stpRNG2', label: 'Step Index 200' },
    { id: 'stpRNG3', label: 'Step Index 300' },
    { id: 'stpRNG4', label: 'Step Index 400' },
    { id: 'stpRNG5', label: 'Step Index 500' },
];
